version: '3'

services:
  jdk11-nanoserver-1809:
    build:
      context: ./11/windows/nanoserver-1809/
      args:
        - VERSION=$REMOTING_VERSION
  jdk17-nanoserver-1809:
    build:
      context: ./17/windows/nanoserver-1809/
      args:
        - VERSION=$REMOTING_VERSION
  jdk11-windowsservercore-ltsc2019:
    build:
      context: ./11/windows/windowsservercore-ltsc2019/
      args:
        - VERSION=$REMOTING_VERSION
  jdk17-windowsservercore-ltsc2019:
    build:
      context: ./17/windows/windowsservercore-ltsc2019/
      args:
        - VERSION=$REMOTING_VERSION
