services:
  jdk11:
    image: ${DOCKERHUB_ORGANISATION}/${DOCKERHUB_REPO}:jdk11-${WINDOWS_FLAVOR}-${WINDOWS_VERSION_TAG}
    build:
      context: ./
      dockerfile: ./windows/${WINDOWS_FLAVOR}/Dockerfile
      args:
        JAVA_HOME: "C:/openjdk-11"
        JAVA_VERSION: 11.0.23+9
        VERSION: ${REMOTING_VERSION}
        WINDOWS_VERSION_TAG: ${WINDOWS_VERSION_TAG}
        TOOLS_WINDOWS_VERSION: ${TOOLS_WINDOWS_VERSION}
      tags:
        - "${DOCKERHUB_ORGANISATION}/${DOCKERHUB_REPO}:${REMOTING_VERSION}-${BUILD_NUMBER}-jdk11-${WINDOWS_FLAVOR}-${WINDOWS_VERSION_TAG}"
  jdk17:
    image: ${DOCKERHUB_ORGANISATION}/${DOCKERHUB_REPO}:jdk17-${WINDOWS_FLAVOR}-${WINDOWS_VERSION_TAG}
    build:
      context: ./
      dockerfile: ./windows/${WINDOWS_FLAVOR}/Dockerfile
      args:
        JAVA_HOME: "C:/openjdk-17"
        JAVA_VERSION: 17.0.11+9
        VERSION: ${REMOTING_VERSION}
        WINDOWS_VERSION_TAG: ${WINDOWS_VERSION_TAG}
        TOOLS_WINDOWS_VERSION: ${TOOLS_WINDOWS_VERSION}
      tags:
        - "${DOCKERHUB_ORGANISATION}/${DOCKERHUB_REPO}:${REMOTING_VERSION}-${BUILD_NUMBER}-jdk17-${WINDOWS_FLAVOR}-${WINDOWS_VERSION_TAG}"
        - "${DOCKERHUB_ORGANISATION}/${DOCKERHUB_REPO}:${REMOTING_VERSION}-${BUILD_NUMBER}-${WINDOWS_FLAVOR}-${WINDOWS_VERSION_TAG}"
        - "${DOCKERHUB_ORGANISATION}/${DOCKERHUB_REPO}:${WINDOWS_FLAVOR}-${WINDOWS_VERSION_TAG}"
  jdk21:
    image: ${DOCKERHUB_ORGANISATION}/${DOCKERHUB_REPO}:jdk21-${WINDOWS_FLAVOR}-${WINDOWS_VERSION_TAG}
    build:
      context: ./
      dockerfile: ./windows/${WINDOWS_FLAVOR}/Dockerfile
      args:
        JAVA_HOME: "C:/openjdk-21"
        JAVA_VERSION: 21+35
        VERSION: ${REMOTING_VERSION}
        WINDOWS_VERSION_TAG: ${WINDOWS_VERSION_TAG}
        TOOLS_WINDOWS_VERSION: ${TOOLS_WINDOWS_VERSION}
      tags:
        - "${DOCKERHUB_ORGANISATION}/${DOCKERHUB_REPO}:${REMOTING_VERSION}-${BUILD_NUMBER}-jdk21-${WINDOWS_FLAVOR}-${WINDOWS_VERSION_TAG}"
