services:
  ## nanoserver
  # 1809
  jdk11-nanoserver-1809:
    image: jdk11-nanoserver-1809
    build:
      context: ./
      dockerfile: ./windows/nanoserver/Dockerfile
      args:
        JAVA_HOME: "C:/openjdk-11"
        JAVA_VERSION: 11.0.20.1_1
        VERSION: ${REMOTING_VERSION}
        WINDOWS_VERSION_TAG: 1809
        TOOLS_WINDOWS_VERSION: 1809
  jdk17-nanoserver-1809:
    image: jdk17-nanoserver-1809
    build:
      context: ./
      dockerfile: ./windows/nanoserver/Dockerfile
      args:
        JAVA_HOME: "C:/openjdk-17"
        JAVA_VERSION: 17.0.8.1_1
        VERSION: ${REMOTING_VERSION}
        WINDOWS_VERSION_TAG: 1809
        TOOLS_WINDOWS_VERSION: 1809
  # ltsc2019
  jdk11-nanoserver-ltsc2019:
    image: jdk11-nanoserver-ltsc2019
    build:
      context: ./
      dockerfile: ./windows/nanoserver/Dockerfile
      args:
        JAVA_HOME: "C:/openjdk-11"
        JAVA_VERSION: 11.0.20.1_1
        VERSION: ${REMOTING_VERSION}
        WINDOWS_VERSION_TAG: ltsc2019
        TOOLS_WINDOWS_VERSION: 1809
  jdk17-nanoserver-ltsc2019:
    image: jdk17-nanoserver-ltsc2019
    build:
      context: ./
      dockerfile: ./windows/nanoserver/Dockerfile
      args:
        JAVA_HOME: "C:/openjdk-17"
        JAVA_VERSION: 17.0.8.1_1
        VERSION: ${REMOTING_VERSION}
        WINDOWS_VERSION_TAG: ltsc2019
        TOOLS_WINDOWS_VERSION: 1809
  # ltsc2022
  jdk11-nanoserver-ltsc2022:
    image: jdk11-nanoserver-ltsc2022
    build:
      context: ./
      dockerfile: ./windows/nanoserver/Dockerfile
      args:
        JAVA_HOME: "C:/openjdk-11"
        JAVA_VERSION: 11.0.20.1_1
        VERSION: ${REMOTING_VERSION}
        WINDOWS_VERSION_TAG: ltsc2022
        TOOLS_WINDOWS_VERSION: ltsc2022
  jdk17-nanoserver-ltsc2022:
    image: jdk17-nanoserver-ltsc2022
    build:
      context: ./
      dockerfile: ./windows/nanoserver/Dockerfile
      args:
        JAVA_HOME: "C:/openjdk-17"
        JAVA_VERSION: 17.0.8.1_1
        VERSION: ${REMOTING_VERSION}
        WINDOWS_VERSION_TAG: ltsc2022
        TOOLS_WINDOWS_VERSION: ltsc2022
  ## windowsservercore
  # 1809
  jdk11-windowsservercore-1809:
    image: jdk11-windowsservercore-1809
    build:
      context: ./
      dockerfile: ./windows/windowsservercore/Dockerfile
      args:
        JAVA_HOME: "C:/openjdk-11"
        JAVA_VERSION: 11.0.20.1_1
        VERSION: ${REMOTING_VERSION}
        WINDOWS_VERSION_TAG: 1809
        TOOLS_WINDOWS_VERSION: 1809
  jdk17-windowsservercore-1809:
    image: jdk17-windowsservercore-1809
    build:
      context: ./
      dockerfile: ./windows/windowsservercore/Dockerfile
      args:
        JAVA_HOME: "C:/openjdk-17"
        JAVA_VERSION: 17.0.8.1_1
        VERSION: ${REMOTING_VERSION}
        WINDOWS_VERSION_TAG: 1809
        TOOLS_WINDOWS_VERSION: 1809
  # ltsc2019
  jdk11-windowsservercore-ltsc2019:
    image: jdk11-windowsservercore-ltsc2019
    build:
      context: ./
      dockerfile: ./windows/windowsservercore/Dockerfile
      args:
        JAVA_HOME: "C:/openjdk-11"
        JAVA_VERSION: 11.0.20.1_1
        VERSION: ${REMOTING_VERSION}
        WINDOWS_VERSION_TAG: ltsc2019
        TOOLS_WINDOWS_VERSION: 1809
  jdk17-windowsservercore-ltsc2019:
    image: jdk17-windowsservercore-ltsc2019
    build:
      context: ./
      dockerfile: ./windows/windowsservercore/Dockerfile
      args:
        JAVA_HOME: "C:/openjdk-17"
        JAVA_VERSION: 17.0.8.1_1
        VERSION: ${REMOTING_VERSION}
        WINDOWS_VERSION_TAG: ltsc2019
        TOOLS_WINDOWS_VERSION: 1809
  # ltsc2022
  jdk11-windowsservercore-ltsc2022:
    image: jdk11-windowsservercore-ltsc2022
    build:
      context: ./
      dockerfile: ./windows/windowsservercore/Dockerfile
      args:
        JAVA_HOME: "C:/openjdk-11"
        JAVA_VERSION: 11.0.20.1_1
        VERSION: ${REMOTING_VERSION}
        WINDOWS_VERSION_TAG: ltsc2022
        TOOLS_WINDOWS_VERSION: ltsc2022
  jdk17-windowsservercore-ltsc2022:
    image: jdk17-windowsservercore-ltsc2022
    build:
      context: ./
      dockerfile: ./windows/windowsservercore/Dockerfile
      args:
        JAVA_HOME: "C:/openjdk-17"
        JAVA_VERSION: 17.0.8.1_1
        VERSION: ${REMOTING_VERSION}
        WINDOWS_VERSION_TAG: ltsc2022
        TOOLS_WINDOWS_VERSION: ltsc2022
