services:
  jdk11-nanoserver:
    image: jdk11-nanoserver-${NANOSERVER_VERSION_NAME}
    build:
      context: ./windows/nanoserver/
      args:
        JAVA_HOME: "C:/openjdk-11"
        JAVA_VERSION: 11.0.20_8
        VERSION: ${REMOTING_VERSION}
        WINDOWS_VERSION_TAG: ${WINDOWS_VERSION_TAG}
  jdk17-nanoserver:
    image: jdk17-nanoserver-${NANOSERVER_VERSION_NAME}
    build:
      context: ./windows/nanoserver/
      args:
        JAVA_HOME: "C:/openjdk-17"
        JAVA_VERSION: 17.0.7_7
        VERSION: ${REMOTING_VERSION}
        WINDOWS_VERSION_TAG: ${WINDOWS_VERSION_TAG}
  jdk11-windowsservercore:
    image: jdk11-windowsservercore-${WINDOWS_VERSION_NAME}
    build:
      context: ./windows/windowsservercore/
      args:
        JAVA_HOME: "C:/openjdk-11"
        JAVA_VERSION: 11.0.20_8
        VERSION: ${REMOTING_VERSION}
        WINDOWS_VERSION_TAG: ${WINDOWS_VERSION_TAG}
  jdk17-windowsservercore:
    image: jdk17-windowsservercore-${WINDOWS_VERSION_NAME}
    build:
      context: ./windows/windowsservercore/
      args:
        JAVA_HOME: "C:/openjdk-17"
        JAVA_VERSION: 17.0.7_7
        VERSION: ${REMOTING_VERSION}
        WINDOWS_VERSION_TAG: ${WINDOWS_VERSION_TAG}
