# Automates creation of Release Drafts using Release Drafter
# Note: additional setup is required, see https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.adoc

name: Release Drafter (Changelog)

on:
  push:
    branches:
      - master
  # Allow to be run manually
  workflow_dispatch:
  # Prepare the new "next release" once a release is created
  release:

# Only allow 1 release-drafter build at a time to avoid creating multiple "next" releases
concurrency: "release-drafter"

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into the default branch
      - uses: release-drafter/release-drafter@v6.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
